# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fulltext_search.interfaces.v1 import fulltext_search_pb2 as fulltext__search__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fulltext_search_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FullTextSearchStub(object):
    """Full-text search service exposing algorithm operations over gRPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Index = channel.unary_unary(
                '/fulltext_search.v1.FullTextSearch/Index',
                request_serializer=fulltext__search__pb2.IndexRequest.SerializeToString,
                response_deserializer=fulltext__search__pb2.IndexResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/fulltext_search.v1.FullTextSearch/Search',
                request_serializer=fulltext__search__pb2.SearchRequest.SerializeToString,
                response_deserializer=fulltext__search__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.CreateFullSearch = channel.unary_unary(
                '/fulltext_search.v1.FullTextSearch/CreateFullSearch',
                request_serializer=fulltext__search__pb2.CreateFullSearchRequest.SerializeToString,
                response_deserializer=fulltext__search__pb2.PageableSearchResponse.FromString,
                _registered_method=True)
        self.GetSearchPage = channel.unary_unary(
                '/fulltext_search.v1.FullTextSearch/GetSearchPage',
                request_serializer=fulltext__search__pb2.GetSearchPageRequest.SerializeToString,
                response_deserializer=fulltext__search__pb2.PageableSearchResponse.FromString,
                _registered_method=True)
        self.Clear = channel.unary_unary(
                '/fulltext_search.v1.FullTextSearch/Clear',
                request_serializer=fulltext__search__pb2.ClearRequest.SerializeToString,
                response_deserializer=fulltext__search__pb2.ClearResponse.FromString,
                _registered_method=True)


class FullTextSearchServicer(object):
    """Full-text search service exposing algorithm operations over gRPC.
    """

    def Index(self, request, context):
        """Index documents into the active search algorithm.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search the index and return ranked hits.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFullSearch(self, request, context):
        """Brute-force search the whole corpus; returns the first pageable page.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSearchPage(self, request, context):
        """Fetch a page from a previously created brute-force search session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Clear(self, request, context):
        """Remove all indexed documents when supported by the algorithm.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FullTextSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Index': grpc.unary_unary_rpc_method_handler(
                    servicer.Index,
                    request_deserializer=fulltext__search__pb2.IndexRequest.FromString,
                    response_serializer=fulltext__search__pb2.IndexResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=fulltext__search__pb2.SearchRequest.FromString,
                    response_serializer=fulltext__search__pb2.SearchResponse.SerializeToString,
            ),
            'CreateFullSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFullSearch,
                    request_deserializer=fulltext__search__pb2.CreateFullSearchRequest.FromString,
                    response_serializer=fulltext__search__pb2.PageableSearchResponse.SerializeToString,
            ),
            'GetSearchPage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSearchPage,
                    request_deserializer=fulltext__search__pb2.GetSearchPageRequest.FromString,
                    response_serializer=fulltext__search__pb2.PageableSearchResponse.SerializeToString,
            ),
            'Clear': grpc.unary_unary_rpc_method_handler(
                    servicer.Clear,
                    request_deserializer=fulltext__search__pb2.ClearRequest.FromString,
                    response_serializer=fulltext__search__pb2.ClearResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fulltext_search.v1.FullTextSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fulltext_search.v1.FullTextSearch', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FullTextSearch(object):
    """Full-text search service exposing algorithm operations over gRPC.
    """

    @staticmethod
    def Index(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fulltext_search.v1.FullTextSearch/Index',
            fulltext__search__pb2.IndexRequest.SerializeToString,
            fulltext__search__pb2.IndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fulltext_search.v1.FullTextSearch/Search',
            fulltext__search__pb2.SearchRequest.SerializeToString,
            fulltext__search__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFullSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fulltext_search.v1.FullTextSearch/CreateFullSearch',
            fulltext__search__pb2.CreateFullSearchRequest.SerializeToString,
            fulltext__search__pb2.PageableSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSearchPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fulltext_search.v1.FullTextSearch/GetSearchPage',
            fulltext__search__pb2.GetSearchPageRequest.SerializeToString,
            fulltext__search__pb2.PageableSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Clear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fulltext_search.v1.FullTextSearch/Clear',
            fulltext__search__pb2.ClearRequest.SerializeToString,
            fulltext__search__pb2.ClearResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
