# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fulltext_search.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'fulltext_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66ulltext_search.proto\x12\x12\x66ulltext_search.v1\"\x96\x01\n\x08\x44ocument\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12<\n\x08metadata\x18\x03 \x03(\x0b\x32*.fulltext_search.v1.Document.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"?\n\x0cIndexRequest\x12/\n\tdocuments\x18\x01 \x03(\x0b\x32\x1c.fulltext_search.v1.Document\"&\n\rIndexResponse\x12\x15\n\rindexed_count\x18\x01 \x01(\x05\"-\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"\xe9\x01\n\x0cSearchResult\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12.\n\x08\x64ocument\x18\x03 \x01(\x0b\x32\x1c.fulltext_search.v1.Document\x12\x12\n\nhighlights\x18\x04 \x03(\t\x12@\n\x08metadata\x18\x05 \x03(\x0b\x32..fulltext_search.v1.SearchResult.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"C\n\x0eSearchResponse\x12\x31\n\x07results\x18\x01 \x03(\x0b\x32 .fulltext_search.v1.SearchResult\"\x0e\n\x0c\x43learRequest\" \n\rClearResponse\x12\x0f\n\x07\x63leared\x18\x01 \x01(\x08\x32\xfd\x01\n\x0e\x46ullTextSearch\x12L\n\x05Index\x12 .fulltext_search.v1.IndexRequest\x1a!.fulltext_search.v1.IndexResponse\x12O\n\x06Search\x12!.fulltext_search.v1.SearchRequest\x1a\".fulltext_search.v1.SearchResponse\x12L\n\x05\x43lear\x12 .fulltext_search.v1.ClearRequest\x1a!.fulltext_search.v1.ClearResponseB\x03\x90\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fulltext_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\000'
  _globals['_DOCUMENT_METADATAENTRY']._loaded_options = None
  _globals['_DOCUMENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHRESULT_METADATAENTRY']._loaded_options = None
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_DOCUMENT']._serialized_start=46
  _globals['_DOCUMENT']._serialized_end=196
  _globals['_DOCUMENT_METADATAENTRY']._serialized_start=149
  _globals['_DOCUMENT_METADATAENTRY']._serialized_end=196
  _globals['_INDEXREQUEST']._serialized_start=198
  _globals['_INDEXREQUEST']._serialized_end=261
  _globals['_INDEXRESPONSE']._serialized_start=263
  _globals['_INDEXRESPONSE']._serialized_end=301
  _globals['_SEARCHREQUEST']._serialized_start=303
  _globals['_SEARCHREQUEST']._serialized_end=348
  _globals['_SEARCHRESULT']._serialized_start=351
  _globals['_SEARCHRESULT']._serialized_end=584
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_start=149
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_end=196
  _globals['_SEARCHRESPONSE']._serialized_start=586
  _globals['_SEARCHRESPONSE']._serialized_end=653
  _globals['_CLEARREQUEST']._serialized_start=655
  _globals['_CLEARREQUEST']._serialized_end=669
  _globals['_CLEARRESPONSE']._serialized_start=671
  _globals['_CLEARRESPONSE']._serialized_end=703
  _globals['_FULLTEXTSEARCH']._serialized_start=706
  _globals['_FULLTEXTSEARCH']._serialized_end=959
# @@protoc_insertion_point(module_scope)
